### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by vanlopes** [PiXeL16/PasswordTextField#11]
Hey!

I implemented this control following the instructions and the eye icon is not showing on IB or in the app, even demo project doesn't work. I ran Debug View Hierarchy and no control is created along with the field.

Here's what my field is set in Interface Builder:
![captura de tela 2016-10-19 as 06 49 15](https://cloud.githubusercontent.com/assets/8545703/19511954/6c225896-95c8-11e6-8710-c07581bd8e43.png)
![captura de tela 2016-10-19 as 06 49 26](https://cloud.githubusercontent.com/assets/8545703/19511957/72f1e2d6-95c8-11e6-9b49-3a43fa29fd30.png)

Tested it with/without delegates, changin border styles, setting a default font, without any controls imported to project (to see if it's having some conflicting libraries) and no cigar.

I'm using XCode 8 with Swift 3, imported the project via CocoaPods (1.0.4).

**Comment by PiXeL16** [comment]
Hum, that's very weird, just used it in personal project and everything worked. Did you found a solution to your problem?.

**Comment by raphaels17** [comment]
same issue here

**Comment by PiXeL16** [comment]
Glad that fixed the issue!
