### ISSUE TITLE
When i add PasswordTextField xCode required describe SWIFT_VERSION

### ISSUE THREAD

**Issue by probovik** [PiXeL16/PasswordTextField#12]
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by bre7** [comment]
You need to use swift 3 in your app.

**Comment by probovik** [comment]
Thank you!
