### ISSUE TITLE
what is the Swift 2.2 branch on Pod 

### ISSUE THREAD

**Issue by korantengNanaYaw** [PiXeL16/PasswordTextField#14]

**Comment by PiXeL16** [comment]
Hey, you should be able to use `1.0.3` with Swift 2.2. Let me know if it works 👍

**Comment by agustinaliagac** [comment]
I added this line to my pod file: 

pod 'PasswordTextField', '~> 1.0.3'

However it doesn't install this version, it installs 1.0.4. Am I missing something ?

**Comment by bre7** [comment]
Try

```ruby
pod 'PasswordTextField', '= 1.0.3'
```

**Comment by agustinaliagac** [comment]
@bre7 , it works now. Thanks !! 👍

**Comment by bre7** [comment]
'~> 1.0.3' will use the most recent version before '1.1'

**Comment by PiXeL16** [comment]
Thanks @bre7 👍
