### ISSUE TITLE
Image doesn't change for custom icon

### ISSUE THREAD

**Issue by dhafinmuktafin** [PiXeL16/PasswordTextField#15]
I have two images with different color (blue and gray) for `CustomShow` and `CustomHide`. The toggle button can be used to show & hide password but the icon always in gray. What should I do to fix that?
Thanks.

**Comment by PiXeL16** [comment]
Hi, 
You are probably not setting the color? You can use:
```passwordTextField.imageTintColor = UIColor.red```
Let me know if that helps 👍

**Comment by PiXeL16** [comment]
Closing due to lack of response, let me know if you have any more problems! Thanks!
