### ISSUE TITLE
module compiled with swift 3.1 cannot be imported in swift 3.2

### ISSUE THREAD

**Issue by ilhamsaputra** [PiXeL16/PasswordTextField#17]
it's really nice if can run in xcode 9 with swift 3.2 or swift 4

Thanks really great and helpful

**Comment by PiXeL16** [comment]
Did you manage to fix this, the pod should work with Xcode 9

**Comment by Ruckt** [comment]
@PiXeL16 you may have forgotten to commit your changes.  There hasn't been a change to the main code body in a year according to the commit records.  It would be great to get it updated soon.

**Comment by PiXeL16** [comment]
There should be a new version `1.0.5` up that supports 3.2 and Xcode 9. There is also a `Swift4` branch.
