### ISSUE TITLE
Swift 4 Compatibility

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [PiXeL16/PasswordTextField#18]
It would be awesome if there is a pod for swift 4

**Comment by bre7** [comment]
The pod is Swift 4 compatible. To disable Swift 3 @objc inference, you need to change 2 lines (use the "Fix me"s provided by Xcode)

**Comment by PiXeL16** [comment]
Nice, also PRs are very welcome to add full Swift 4 compatibility. 🙇
