### ISSUE TITLE
Swift 4.2 compatibility

### ISSUE THREAD

**Issue by Schaefers** [PiXeL16/PasswordTextField#23]
I think a few fix me clicks will be sufficient.

**Comment by PiXeL16** [comment]
There is a Swift4 branch. Is that working for you?

**Comment by Schaefers** [comment]
No, because there are some function name changes from 4.0 to 4.2

**Comment by SergeyPetrachkov** [comment]
I've submitted a PR

**Comment by PiXeL16** [comment]
Merged
