### ISSUE TITLE
Having trouble setting it up through Carthage

### ISSUE THREAD

**Issue by surpher** [PiXeL16/PasswordTextField#25]
Following the README.md installation using Carthage I am constantly being presented with `Build Failed` exit.

The last messages in the log are as follows:
```
Build system information
error: /Users/user/folder/project/Carthage/Checkouts/PasswordTextField/Pods/Target Support Files/Pods-PasswordTextField/Pods-PasswordTextField.release.xcconfig: unable to open file (in target "PasswordTextField" in project "PasswordTextField") (in target 'PasswordTextField')

** ARCHIVE FAILED **
```

I've cloned the PasswordTextField project, cleaned a few Pod references, added Quick&Nimble dependencies to Cartfile, build and ran the demo project without problems. 

Then used my local project as dependency for my project... still no luck.

Any tips on how to resolve this would be much appreciated.

**Comment by surpher** [comment]
Nevermind. Forked v1.2 @ [surpher/PasswordTextField](https://github.com/surpher/PasswordTextField) with Carthage only support.

**Comment by PiXeL16** [comment]
Interesting, whats the change on your fork?. Happy to merge this if it makes sense.

**Comment by surpher** [comment]
Removed every single Cocoapods reference and now I have a clean project that builds a framework. Not sure it'd make sense to to merge now.
