### ISSUE TITLE
Eye icon getting hidden when text field not become a first responder

### ISSUE THREAD

**Issue by digrase008** [PiXeL16/PasswordTextField#28]
It is working fine for me but when my text field is not become a first responder that time the eye Icon is getting hidden again when I click on text field when it is become a first responder again it is showing me

Expected behaviour: 

My Login Form contain 1) User Id  2) Password  and 3) PAN/DOB, both Password and PAN/DOB fields are Secure text entry on this text fields I added PasswordTextField pod but when this text fields are not become a first responder the eye icon getting hidden. I want to keep that eye icon highlighted for all the time. Is there any way to do so.

**Comment by PiXeL16** [comment]
I was not able to reproduce, please reopen with the newer version if this is still an issue!
