### ISSUE TITLE
Xcode reports "Couldn't find Assets.car"

### ISSUE THREAD

**Issue by nashish** [PiXeL16/PasswordTextField#29]
Since updating to Xcode 11.1 and iOS 13, (that's when I started to notice it anyway, not certain that this is the root cause) I'm seeing the following warning logged twice each time a PasswordTextField is rendered on a given iOS screen:

`[framework] CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.PasswordTextField'`

**Comment by PiXeL16** [comment]
Probably related to #27

**Comment by ricky641b** [comment]
@PiXeL16 Also as of Xcode 15 and iOS 17 this issue is not occuring so it can be closed

**Comment by PiXeL16** [comment]
Thanks!
