### ISSUE TITLE
how to use this with carthage file

### ISSUE THREAD

**Issue by commando24** [PiXeL16/PasswordTextField#3]
I am getting this error while i'm trying to update my cart file.
Parse error: invalid GitHub repository identifier "PasswordTextField"
Please clarify .

**Comment by PiXeL16** [comment]
```github "PiXeL16/PasswordTextField"``` should work. No?

**Comment by commando24** [comment]
Yeah its working...👍🏻

**Comment by PiXeL16** [comment]
Nice to hear that. Closing for now, Let me know if you have any more issues!
