### ISSUE TITLE
Xcode 15 error: "Stored properties cannot be marked unavailable with '@available'"

### ISSUE THREAD

**Issue by uri2x** [PiXeL16/PasswordTextField#34]
When using the library with Xcode 15 we get a build error as above, pointing to PasswordTextField.swift:86

**Comment by PiXeL16** [comment]
I am afriad I have stopped mantaining this library for quite some time now. If you have time to look into the issue that would be appreciated. PRs are welcome

**Comment by PiXeL16** [comment]
Should be fixed by #35
