### ISSUE TITLE
Unknown class PasswordTextField in interface builder file.

### ISSUE THREAD

**Issue by commando24** [PiXeL16/PasswordTextField#4]
when i am setting class for textfield in storyboard its showing "Unknown class".but when i am creating textfield with the class "PasswordTextField" its working fine.Here is an image...see this.
![screen shot 2016-07-28 at 10 19 12 am](https://cloud.githubusercontent.com/assets/15805487/17201589/857313dc-54ad-11e6-8e16-aad5171eb598.png)

**Comment by PiXeL16** [comment]
Thanks for the info. Maybe something to do with Carthage? Can you try with CocoaPods and let me know if it works?

**Comment by PiXeL16** [comment]
Closing due to lack of response. Let me know if you have more issues.
Thanks!

**Comment by commando24** [comment]
Sry for that.but it was not working with swift 3 but its working perfectly fine with swift 2.

**Comment by PiXeL16** [comment]
Thanks, Swift3 Branch is in development at #7. In case you want to give us a hand. 👍

**Comment by agustinaliagac** [comment]
In case someone else has this issue:

![screen shot 2016-12-04 at 4 58 51 pm](https://cloud.githubusercontent.com/assets/6007290/20868799/109017b2-ba43-11e6-9fd3-3ea2f3beb40a.png)

In the storyboard, I had "Module" set to "None" and had the same issue described in this ticket.
Then I changed it to "PasswordTextField" and now it works.

**Comment by PiXeL16** [comment]
Nice 👍

**Comment by freakdragon** [comment]
Thank's a lot. Setting module worked for me too in my swift 3. May be, it has to be added to description of installing of this module?

**Comment by PiXeL16** [comment]
Good point, will add to the `ReadMe`.
