### ISSUE TITLE
Better Installation Section

### ISSUE THREAD

**Issue by lfarah** [PiXeL16/PasswordTextField#5]
Hey @PiXeL16, your library is really interesting.

The only problem I found was the ```README.md```, which can have a better **Installation Section**
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize the **Installation Section**
If you want, I can help you to do it.

What are your thoughts?

**Comment by PiXeL16** [comment]
Hey @lfarah sure thing! All `PR` are welcome. You are right about the installation section. Since I normally just use `CocoaPods` most of my projects are lacking on that area.
Thanks!
