### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nschucky** [PiXeL16/PasswordTextField#7]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by PiXeL16** [comment]
Hey @nschucky. You are right, I need to work in the Swift3 Version. `Swift3` branch has been created. Thanks for the help 🤗!

**Comment by PiXeL16** [comment]
@nschucky There is now a Swift 3 merged branch thanks to the awesome work from @bre7. So closing for now. Thanks!
